permalink: /:categories/:title.html
# url: "https://wwideapp.github.io/"
full_name: "Cool App"
first_name: "Cool"
last_name: "App"
blog_title: "Cool App"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "Cool App"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Find Cool App"
twitter: ""
github: ""
facebook: ""
linkined_url: ""
